### ISSUE TITLE
License file for api implementation

### ISSUE THREAD

**Issue by vigalo** [regulaforensics/DocumentReader-Cordova-Plugin#3]
Hello :

I don't understand where I must place the license file if only need to use the api and not build the sample app. It must be placed in DocumentReader/www anyway?

Thanks.

**Comment by vyakimchik** [comment]
Hello,

Document Reader SDK consists of 2 parts: API and Core. Both of them are required. The `regula.license` file should be placed in the `www` folder. Please, take a look at our demo project to integrate the SDK correctly into your application.

Links to the documentation:
* https://docs.regulaforensics.com/cordova/core
* https://docs.regulaforensics.com/cordova/scenarios
