### ISSUE TITLE
init failed: /DocumentReaderCore.framework is missed

### ISSUE THREAD

**Issue by vigalo** [regulaforensics/DocumentReader-Cordova-Plugin#6]
Hello :

My app is working fine in android. Now I'm trying to use in iOS. Project compiles and works as expected but when I try to scan a document I get this error:

init failed: /DocumentReaderCore.framework is missed

The full core beta is installed and is working fine in android.

Thanks

**Comment by vyakimchik** [comment]
Hello,

In case "`DocumentReaderCore.framework` is missed" error is encountered, do the following: go to the `Frameworks, Libraries, and Embedded Content` on the General Tab of the target. Remove `DocumentReaderCore.framework`. Then add the framework once again (`ios/DocumentReader/Plugins/cordova-plugin-document-reader-core-fullrfid/`).
